name: run New_home.py

on:
  schedule:
    - cron: '* 19 * * *'  # Este cron se ejecutar치 cada 5'

jobs:
  run-script:
    runs-on: ubuntu-latest  # Ejecuta el script en una m치quina Ubuntu

    steps:
      - uses: actions/checkout@v2  # Clona el repositorio

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Configura Python 3.x en la m치quina
      
      - name: Install distutils
        run: sudo apt-get install python3-distutils

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        continue-on-error: true 

      - name: Download Excel file
        run: wget -O New_home.xlsx "https://github.com/iAleix/New_home-/raw/112648ab436d7d3dd7a326695b7fbe47cd13f945/New_home.xlsx"

      - name: Run Python script
        run: python New_home.py  # Ejecuta el script Python que subiste

      - name: Commit and push changes  # A침ade este paso para hacer commit y push de los cambios en el Excel
        run: |
          git config --local user.email "aleix.borrella.colome@gmail.com"
          git config --local user.name "Aleix"
          git add New_home.xlsx  # Incluye el archivo original
          git add New_home_*.xlsx  # Incluye la copia con fecha
          git commit -m "Update Excel with new data"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Usa el token para autenticar y hacer push
